[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.24"
evm-version = "cancun"
optimizer = true
optimizer-runs = 200
via-ir = true
gas_reports = ["*"]

[profile.default.zksync]
compile = true
fallback_oz = true
mode = '3'
