[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.24"

[profile.zksync]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.24"
compile = true
fallback_oz = true
mode = '3'
